// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qliltpkoqtyaeszwzamu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsaWx0cGtvcXR5YWVzend6YW11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2NTUwNDEsImV4cCI6MjA3MzIzMTA0MX0.B1gje1hoqIPsmb6031hYsZ90v2RHVQ73eu9a-Xo-js8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});